### PR TITLE
Merge with FleCSI master + fix for boost

### PR DESCRIPTION
**Pull request by ipdemes**
@hkaiser : In this branch I am trying to fix Boost error you were seeing when building FleCSI +  merged your branch with the most recent FLeCSI master.

### CODE REVIEW

**Comment by hkaiser** [comment]
@ipdemes could you rebase this, please?

**Comment by ipdemes** [comment]
@hkaiser : I have tried doing that Yesterday but there were some issues (tests fail after merge). I will try to fix that in the afternoon.

**Comment by ipdemes** [comment]
@hkaiser : I have just rebased my branch. Could you, please, check it?

**Comment by hkaiser** [comment]
@ipdemes there are still conflicts, so I can't merge it...

**Comment by ipdemes** [comment]
@hkaiser : OK, I have just resolved the conflicts.

**Comment by hkaiser** [comment]
Thanks a lot, Irina!

**Comment by ipdemes** [comment]
Sure! I hope we will get it in FleCSI master soon

**Pull request merged**
